name: Template - Collect Results

on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string

jobs:
  collect-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Download JSON artifacts
        uses: actions/download-artifact@v4
        with:
          path: results/
          pattern: ${{ inputs.exp-name }}_*

      - name: Print summary
        run: python3 utils/summarize.py results/ ${{ inputs.exp-name }} >> $GITHUB_STEP_SUMMARY

      - name: Aggregate results
        run: python3 utils/collect_results.py results/ ${{ inputs.exp-name }}

      - name: Upload aggregated results
        uses: actions/upload-artifact@v4
        with:
          name: results_${{ inputs.exp-name }}
          path: agg_${{ inputs.exp-name }}.json

      - name: Plot performance
        run: |
          pip install -q matplotlib
          python3 utils/plot_perf.py results/ ${{ inputs.exp-name }}

      - name: Upload performance graphs
        uses: actions/upload-artifact@v4
        with:
          name: graphs_${{ inputs.exp-name }}
          path: |
            tput_vs_intvty_*_${{ inputs.exp-name }}.png
            tput_vs_e2el_*_${{ inputs.exp-name }}.png
