name: Test - Full Sweep

concurrency:
  group: benchmark-lock
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      run_1k1k:
        type: boolean
        required: false
      run_8k1k:
        type: boolean
        required: false
      run_1k8k:
        type: boolean
        required: false

      use_h100:
        type: boolean
        required: false
      use_h200:
        type: boolean
        required: false
      use_b200:
        type: boolean
        required: false
      use_mi300x:
        type: boolean
        required: false
      use_mi325x:
        type: boolean
        required: false
      use_mi355x:
        type: boolean
        required: false

jobs:
  mega-test-run:
    uses: ./.github/workflows/full-sweep-tmpl.yml
    secrets: inherit
    with:
      run_1k1k: ${{ inputs.run_1k1k }}
      run_8k1k: ${{ inputs.run_8k1k }}
      run_1k8k: ${{ inputs.run_1k8k }}
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  calc-success-rate:
    needs: mega-test-run
    if: ${{ always() && !cancelled() }}
    runs-on: ubuntu-latest

    env:
      RESULTS_DIR: "results/"
      STATS_FILENAME: "run_stats"

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Download results artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.RESULTS_DIR }}
          pattern: results_*

      - name: Calculate success rate
        run: python3 utils/calc_success_rate.py $RESULTS_DIR $STATS_FILENAME

      - uses: actions/upload-artifact@v4
        with:
          name: "run-stats"
          path: ${{ env.STATS_FILENAME }}.json
