name: Template - Full Sweep

on:
  workflow_call:
    inputs:
      run_1k1k:
        type: boolean
        required: true
      run_8k1k:
        type: boolean
        required: true
      run_1k8k:
        type: boolean
        required: true

      use_h100:
        type: boolean
        required: true
      use_h200:
        type: boolean
        required: true
      use_b200:
        type: boolean
        required: true
      use_mi300x:
        type: boolean
        required: true
      use_mi325x:
        type: boolean
        required: true
      use_mi355x:
        type: boolean
        required: true
      use_gb200:
        type: boolean
        required: false
        default: false

jobs:
  _70b-1k1k:
    if: ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-70b-1k1k-results:
    needs: _70b-1k1k
    if: ${{ inputs.run_1k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: '70b_1k1k'

  dsr1-1k1k:
    if: ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-dsr1-1k1k-results:
    needs: dsr1-1k1k
    if: ${{ inputs.run_1k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k1k'

  dsr1-multinode-1k1k-mtp-off:
    if: ${{ inputs.run_1k1k && inputs.use_gb200 }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_multinode_1k1k_mtp_off'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_h200: false
      use_b200: false
      use_mi300x: false
      use_mi325x: false
      use_mi355x: false
      use_gb200: ${{ inputs.use_gb200 }}
      mtp-mode: 'off'

  collect-dsr1-multinode-1k1k-mtp-off-results:
    needs: dsr1-multinode-1k1k-mtp-off
    if: ${{ inputs.run_1k1k && inputs.use_gb200 && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_multinode_1k1k_mtp_off'

  dsr1-multinode-1k1k-mtp-on:
    if: ${{ inputs.run_1k1k && inputs.use_gb200 }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_multinode_1k1k_mtp_on'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_h200: false
      use_b200: false
      use_mi300x: false
      use_mi325x: false
      use_mi355x: false
      use_gb200: ${{ inputs.use_gb200 }}
      mtp-mode: 'on'

  collect-dsr1-multinode-1k1k-mtp-on-results:
    needs: dsr1-multinode-1k1k-mtp-on
    if: ${{ inputs.run_1k1k && inputs.use_gb200 && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_multinode_1k1k_mtp_on'

  gptoss-1k1k:
    if: ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/gptoss-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-1k1k-results:
    needs: gptoss-1k1k
    if: ${{ inputs.run_1k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k1k'

  _70b-8k1k:
    if: ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-70b-8k1k-results:
    needs: _70b-8k1k
    if: ${{ inputs.run_8k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: '70b_8k1k'

  dsr1-8k1k:
    if: ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-dsr1-8k1k-results:
    needs: dsr1-8k1k
    if: ${{ inputs.run_8k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_8k1k'

  dsr1-multinode-8k1k-mtp-off:
    if: ${{ inputs.run_8k1k && inputs.use_gb200 }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_multinode_8k1k_mtp_off'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h200: false
      use_b200: false
      use_mi300x: false
      use_mi325x: false
      use_mi355x: false
      use_gb200: ${{ inputs.use_gb200 }}
      mtp-mode: 'off'

  collect-dsr1-multinode-8k1k-mtp-off-results:
    needs: dsr1-multinode-8k1k-mtp-off
    if: ${{ inputs.run_8k1k && inputs.use_gb200 && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_multinode_8k1k_mtp_off'

  dsr1-multinode-8k1k-mtp-on:
    if: ${{ inputs.run_8k1k && inputs.use_gb200 }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_multinode_8k1k_mtp_on'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h200: false
      use_b200: false
      use_mi300x: false
      use_mi325x: false
      use_mi355x: false
      use_gb200: ${{ inputs.use_gb200 }}
      mtp-mode: 'on'

  collect-dsr1-multinode-8k1k-mtp-on-results:
    needs: dsr1-multinode-8k1k-mtp-on
    if: ${{ inputs.run_8k1k && inputs.use_gb200 && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_multinode_8k1k_mtp_on'

  gptoss-8k1k:
    if: ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/gptoss-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-8k1k-results:
    needs: gptoss-8k1k
    if: ${{ inputs.run_8k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_8k1k'

  _70b-1k8k:
    if: ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-70b-1k8k-results:
    needs: _70b-1k8k
    if: ${{ inputs.run_1k8k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: '70b_1k8k'

  dsr1-1k8k:
    if: ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/dsr1-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-dsr1-1k8k-results:
    needs: dsr1-1k8k
    if: ${{ inputs.run_1k8k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_1k8k'

  gptoss-1k8k:
    if: ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/gptoss-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
      use_h100: ${{ inputs.use_h100 }}
      use_h200: ${{ inputs.use_h200 }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-1k8k-results:
    needs: gptoss-1k8k
    if: ${{ inputs.run_1k8k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k8k'
