name: Template - gpt-oss

on:
  workflow_dispatch:
    inputs:
      exp-name:
        required: true
        type: string
      isl:
        required: true
        type: string
      osl:
        required: true
        type: string
      max-model-len:
        required: true
        type: string
      random-range-ratio:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 180

jobs:
  bmk-h100:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: h100
      image: 'kedarpotdar147/vllm0.1:latest'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      timeout: ${{ inputs.timeout }}
      framework: 'vllm'
      precision: 'fp4'

  bmk-h200:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: h200
      image: 'kedarpotdar147/vllm0.1:latest'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      timeout: ${{ inputs.timeout }}
      framework: 'vllm'
      precision: 'fp4'

  bmk-h200-trt:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: h200-trt
      image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'  
      timeout: ${{ inputs.timeout }}
      framework: 'trt'
      precision: 'fp4'

  bmk-b200:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: b200
      image: 'kedarpotdar147/vllm:05'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2]'  
      timeout: ${{ inputs.timeout }}
      framework: 'vllm'
      precision: 'fp4'

  bmk-b200-trt:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: b200-trt
      image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post1'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2]'  
      timeout: ${{ inputs.timeout }}
      framework: 'trt'
      precision: 'fp4'

  bmk-mi300x:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi300x
      image: 'vllm rocm/vllm-dev:open-mi300-08052025'
      model: 'amd/Llama-3.3-70B-Instruct-FP8-KV'
      tp-list: '[1, 2, 4, 8]'
      timeout: ${{ inputs.timeout }}
      framework: 'vllm'
      precision: 'fp4'

  bmk-mi325x:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi325x
      image: 'vllm rocm/vllm-dev:open-mi300-08052025'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      timeout: ${{ inputs.timeout }}
      framework: 'vllm'
      precision: 'fp4'

  bmk-mi355x:
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi355x
      image: 'rocm/vllm-dev:open-mi355-08052025'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1]'
      timeout: ${{ inputs.timeout }}
      framework: 'vllm'
      precision: 'fp4'

  collect-results:
    needs: [ bmk-h200, bmk-h200-trt, bmk-b200, bmk-b200-trt, bmk-mi300x, bmk-mi325x]  
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
