name: Test - Local Gaudi3 70B Only

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  local-gaudi3-70b-test:
    uses: ./.github/workflows/70b-tmpl.yml
    secrets: inherit
    with:
      exp-name: '70b_8k1k_local'  # ‚Üê Changed from 'gaudi3-test-70b' to '70b_1k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_gaudi3: true
      use_h100: false
      use_h200: false
      use_b200: false
      use_mi300x: false
      use_mi325x: false
      use_mi355x: false
